rushpickme/src/main/resources/application.properties
=> DB URL 주소 변경

rushpickme/src/main/java/com/kh/rushpickme/controller/FileDownloadController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/TestController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/AttachDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/AttachDto.java, rushpickme/src/main/java/com/kh/rushpickme/dto/PickDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/AttachMapper.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickMapper.java, rushpickme/src/main/java/com/kh/rushpickme/service/AttachService.java
testController 삭제 및 Pick/Attach DTO DAO Mapper 생성
=> testController 삭제 및 Pick/Attach DTO DAO Mapper 생성

rushpickme/src/main/java/com/kh/rushpickme/dao/PointDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/PointDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PointMapper.java
PointDao, PointDto, PointMapper 생성
=> PointDao, PointDto, PointMapper 생성

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/resources/static/css/commons.css, rushpickme/src/main/webapp/WEB-INF/views/pick/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
commons.css / pick list.jsp 생성
=> commons.css / pick list 생성

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminPointController.java
AdminPointController 구현 
저도 승인해주세요
=> AdminPointController 구현

rushpickme/src/main/java/com/kh/rushpickme/controller/ApplyController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/ApplyDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/ApplyMapper.java, rushpickme/src/main/webapp/WEB-INF/views/apply/request.jsp
=> apply 기능 구현

rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/MemberGreenDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/MemberGreenMapper.java
=> 회원가입 오류 수정

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/webapp/WEB-INF/views/admin/member/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/edit.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/add.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/edit.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/list.jsp
AdminController(아직 미완성), point-add, detail, edit, member-search 승인해주쇼
=> AdminController(아직 미완성), point-add, detail, edit, member-search

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java
AdminController 오류없는 거 일단 올립니다 
오전에 디자인 좀 만져야해서 나중에 하겠습니다람쥐
=> AdminController 오류없는 거

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/PickDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickFinishVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickFinishVo.java, rushpickme/src/main/webapp/WEB-INF/views/pick/list.jsp
=> 수거현황 페이지 구현 완료

rushpickme/src/main/webapp/WEB-INF/views/member/signUp.jsp
=> 버튼 클릭에 따른 회원가입페이지 이동 구현

rushpickme/src/main/java/com/kh/rushpickme/dao/QnaDao.java
=> qna 수정 업로드

rushpickme/src/main/java/com/kh/rushpickme/mapper/QnaListMapper.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/QnaMapper.java, rushpickme/src/main/webapp/WEB-INF/views/pick/reject.jsp
=> mapper수정 등

rushpickme/src/main/java/com/kh/rushpickme/dao/ReviewLikeDao.java, rushpickme/src/main/java/com/kh/rushpickme/vo/LikeVO.java
=> LikeVO reviewLikeDao 생성

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/PointController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PointDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/PointDto.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PointMapper.java, rushpickme/src/main/webapp/WEB-INF/views/admin/member/edit.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/greenList.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/pickerList.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/add.jsp, rushpickme/src/main/webapp/WEB-INF/views/point/charge.jsp, rushpickme/src/main/webapp/WEB-INF/views/point/chargeFinish.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
pointController, MemberDao, pickerList, greenList, header, charge
=> pointController, MemberDao, pickerList, greenList, header, charge,

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickWaitVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickWaitVo.java, rushpickme/src/main/webapp/WEB-INF/views/pick/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/reject.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitDetail.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitList.jsp
=> 수거대기 리스트화면 구현, 수거거부 화면구현

rushpickme/pom.xml, rushpickme/src/main/java/com/kh/rushpickme/service/EmailService.java, rushpickme/src/main/resources/application.properties
=> 프로젝트 스타터 기능 추가 및 EmailService 구현중

rushpickme/src/main/java/com/kh/rushpickme/controller/ApplyController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/resources/static/js/commons.js, rushpickme/src/main/webapp/WEB-INF/views/apply/request.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
=> 헤더, applyDao 수정

rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java
=> 아이디 찾기 기능 구현

rushpickme/src/main/java/com/kh/rushpickme/controller/QnaController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/ReviewController.java, rushpickme/src/main/java/com/kh/rushpickme/dto/QnaDto.java, rushpickme/src/main/webapp/WEB-INF/views/qna/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/navigator.jsp
=> list.jsp navigator 등등 수정

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/webapp/WEB-INF/views/pick/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitList.jsp
=> pick 이것저것 수정..

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/webapp/WEB-INF/views/pick/reject.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitDetail.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitList.jsp
=> Pick 리스트 페이징기능 추가, 거부기능 수정

rushpickme/src/main/java/com/kh/rushpickme/dao/QnaDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ReplyDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/ReplyDto.java, rushpickme/src/main/java/com/kh/rushpickme/interceptor/QnaHitsInterceptor.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/ReplyMapper.java, rushpickme/src/main/webapp/WEB-INF/views/qna/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/qna/edit.jsp, rushpickme/src/main/webapp/WEB-INF/views/qna/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/qna/write.jsp
=> shw 신형우 승인

rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java, rushpickme/src/main/webapp/WEB-INF/views/member/changeAccount.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/changePassword.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/completePassword.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/mypage.jsp
=> 마이페이지 및 여러가지 기능 구현

rushpickme/src/main/java/com/kh/rushpickme/configuration/InterceptorConfiguration.java, rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/QnaController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickProceedVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickProceedVo.java, rushpickme/src/main/resources/static/css/commons.css, rushpickme/src/main/webapp/WEB-INF/views/pick/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/proceedList.jsp
수거진행리스트 추가, interceptorConfiguration 생성
=> 수저진행리스트 추가, interceptorConfiguration 생성

rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java
=> membercontroller 뭔가 수정됨..

rushpickme/src/main/java/com/kh/rushpickme/controller/ReviewController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ReviewDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/ReviewDto.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PageVO.java, rushpickme/src/main/webapp/WEB-INF/views/review/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/review/write.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/navigator.jsp
=> list vo dao dto 등등

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickProceedVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickWaitVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickFinishVo.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickProceedVo.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickWaitVo.java, rushpickme/src/main/webapp/WEB-INF/views/pick/finishList.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/proceedList.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitDetail.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitList.jsp
=> 모든페이지 날짜 자료형 수정

rushpickme/src/main/java/com/kh/rushpickme/dao/ReviewDao.java, rushpickme/src/main/webapp/WEB-INF/views/review/write.jsp
=> reviewDao write.jsp

rushpickme/src/main/webapp/WEB-INF/views/home.jsp, rushpickme/src/main/webapp/WEB-INF/views/point/charge.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
=> 홈 없앴고 헤더 구현했습니다 홈은 익일 구현하겠습니당

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/AdminDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java, rushpickme/src/main/webapp/WEB-INF/views/admin/member/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/edit.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
admin controller, dao, edtail, edit header, memberDao, search 수정 관리자만 볼수있게끔 헤더 수정
=> admin controller, dao, edtail, edit header, memberDao, search 수정 관리자만

rushpickme/src/main/resources/static/css/commons.css
=> 네비게이터off변경

rushpickme/src/main/webapp/WEB-INF/views/member/changePassword.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/login2.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/myPageGreen.jsp, rushpickme/src/main/webapp/WEB-INF/views/member/myPagePick.jsp
=> 뭘 수정 한지 모르겠지만 업로드

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/webapp/WEB-INF/views/admin/member/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/pickerlist.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp
search, detail 바탕(흰색), hover(beige) 변경
=> search, detail 바탕(흰색), hover(beige) 변경

rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
=> 타이틀 누르면 홈화면 넘어가게끔 수정

rushpickme/src/main/webapp/WEB-INF/views/home.jsp
=> 홈화면 다시 구현했습니당

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/webapp/WEB-INF/views/pick/accept.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/complete.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/finishList.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/reject.jsp
=> 이미지 미리보기 구현

rushpickme/src/main/webapp/WEB-INF/views/home.jsp
=> 홈 이미지 슬라이드 구현 수정

rushpickme/src/main/webapp/WEB-INF/views/apply/requestDetail.jsp
=> requestDetail수정

rushpickme/src/main/resources/static/css/layout.css, rushpickme/src/main/webapp/WEB-INF/views/home.jsp
홈화면, 레이아웃 설정 2차 수정합니다 아직 수정 더 남았습니다
=> 홈화면, 레이아웃 설정

rushpickme/src/main/webapp/WEB-INF/views/home.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
헤더 글씨체 색깔 수정, 홈화면 최종_찐최종 수정 제발 마지막 최종
=> 헤더 글씨체 색깔 수정, 홈화면 최종_찐최종 수정 제발 마지막 최종

rushpickme/src/main/java/com/kh/rushpickme/controller/ApplyController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/ApplyListVOMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/ApplyListVO.java, rushpickme/src/main/webapp/WEB-INF/views/apply/applyDetail.jsp, rushpickme/src/main/webapp/WEB-INF/views/apply/applyList.jsp, rushpickme/src/main/webapp/WEB-INF/views/apply/stateList.jsp
=> 신청 목록 -> 수거 진행사항

rushpickme/src/main/java/com/kh/rushpickme/controller/PickController.java, rushpickme/src/main/java/com/kh/rushpickme/dto/PickDto.java, rushpickme/src/main/java/com/kh/rushpickme/restcontroller/MemberRestController.java, rushpickme/src/main/java/com/kh/rushpickme/service/EmailService.java, rushpickme/src/main/webapp/WEB-INF/views/pick/complete.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/reject.jsp, rushpickme/src/main/webapp/WEB-INF/views/pick/waitDetail.jsp
=> 이메일센더수정 pickDto수정

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/PointController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/AdminDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/vo/StatVO.java, rushpickme/src/main/webapp/WEB-INF/views/admin/check/apply.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/check/pick.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
=> header, pick, apply jsp 수정

rushpickme/src/main/java/com/kh/rushpickme/controller/ReviewController.java, rushpickme/src/main/java/com/kh/rushpickme/restcontroller/QnaAttachRestController.java, rushpickme/src/main/java/com/kh/rushpickme/restcontroller/ReviewAttachRestController.java, rushpickme/src/main/webapp/WEB-INF/views/qna/write.jsp, rushpickme/src/main/webapp/WEB-INF/views/review/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/review/list.jsp, rushpickme/src/main/webapp/WEB-INF/views/review/write.jsp
=> review qna

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/webapp/WEB-INF/views/admin/check/apply.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/check/pick.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
지혜야 이제 url안쳐도돼..@!!!!!!!!!!!!!!
=> 지혜야 이제 url안쳐도돼..

rushpickme/src/main/java/com/kh/rushpickme/controller/ApplyController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/webapp/WEB-INF/views/apply/applyDetail.jsp, rushpickme/src/main/webapp/WEB-INF/views/apply/request.jsp
=> 아직 취소는 못함 ( 취소에 번호가 들어가구 들어간 번호는 리스트에 안뜨게 해야함)

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/ApplyDao.java, rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/ApplyListMapper.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PageVO.java, rushpickme/src/main/webapp/WEB-INF/views/admin/check/apply.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/check/pick.jsp, rushpickme/src/main/webapp/WEB-INF/views/template/pickPageNavigator.jsp
관리자메뉴에서 수거관리와 신청관리 페이징 드디어 성공^^
=> 관리자메뉴에서 수거관리와 신청관리 페이징 드디어 성공^^

rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java, rushpickme/src/main/java/com/kh/rushpickme/dto/MemberGreenDto.java, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp
=> 드디어 완성했슈.. 부름티켓..

rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java
부름티켓 차등지급 구현 없이 만원당 한장 구현했습니다.
=> 부름티켓 차등지급 구현 없이 만원당 한장 구현했습니다.

rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/PointController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java
기존 부름티켓 3장에서 포인트 구매시 차등지급되는 티켓수 증가 구현했습니다(만원당 한장씩)
=> 기존 부름티켓 3장에서 포인트 구매시 차등지급되는 티켓수 증가 구현했습니다(만원당 한장씩)

rushpickme/src/main/java/com/kh/rushpickme/controller/PointController.java, rushpickme/src/main/webapp/WEB-INF/views/template/header.jsp
header, pointController 수정했음용ㅋ
=> header, pointController 수정했음용ㅋ

rushpickme/src/main/webapp/WEB-INF/views/admin/member/detail.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/member/search.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/add.jsp, rushpickme/src/main/webapp/WEB-INF/views/admin/point/list.jsp
=> 버튼 색깔 다 바꿈

rushpickme/src/main/java/com/kh/rushpickme/controller/KakaoLoginController.java, rushpickme/src/main/java/com/kh/rushpickme/controller/MemberController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/MemberDao.java
=> 준오빠 업적 올립니다

rushpickme/src/main/java/com/kh/rushpickme/controller/AdminController.java, rushpickme/src/main/java/com/kh/rushpickme/dao/AdminDao.java
=> admin 필요없는거지웠습니다

rushpickme/src/main/java/com/kh/rushpickme/dao/PickDao.java, rushpickme/src/main/java/com/kh/rushpickme/mapper/PickFinishRestVoMapper.java, rushpickme/src/main/java/com/kh/rushpickme/restcontroller/PickRestController.java, rushpickme/src/main/java/com/kh/rushpickme/vo/PickFinishRestVo.java, rushpickme/src/main/webapp/WEB-INF/views/pick/finishList.jsp
=> 오름차슌내림차슌~~
